"""Add risk_score and ai_summary to variants

Revision ID: 851eb49e4f84
Revises: 
Create Date: 2026-02-26 22:48:07.785835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '851eb49e4f84'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variants', sa.Column('gene_symbol', sa.String(length=100), nullable=True))
    op.add_column('variants', sa.Column('transcript_id', sa.String(length=100), nullable=True))
    op.add_column('variants', sa.Column('consequence', sa.String(length=200), nullable=True))
    op.add_column('variants', sa.Column('protein_change', sa.String(length=200), nullable=True))
    op.add_column('variants', sa.Column('clinvar_significance', sa.String(length=200), nullable=True))
    op.add_column('variants', sa.Column('clinvar_review_status', sa.String(length=200), nullable=True))
    op.add_column('variants', sa.Column('clinvar_condition', sa.Text(), nullable=True))
    op.add_column('variants', sa.Column('gnomad_af', sa.Float(), nullable=True))
    op.add_column('variants', sa.Column('gnomad_ac', sa.Integer(), nullable=True))
    op.add_column('variants', sa.Column('gnomad_an', sa.Integer(), nullable=True))
    op.add_column('variants', sa.Column('annotation_status', sa.String(length=50), nullable=True))
    op.add_column('variants', sa.Column('annotated_at', sa.DateTime(), nullable=True))
    op.add_column('variants', sa.Column('risk_score', sa.Integer(), nullable=True))
    op.add_column('variants', sa.Column('ai_summary', sa.Text(), nullable=True))
    op.create_index(op.f('ix_variants_risk_score'), 'variants', ['risk_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_variants_risk_score'), table_name='variants')
    op.drop_column('variants', 'ai_summary')
    op.drop_column('variants', 'risk_score')
    op.drop_column('variants', 'annotated_at')
    op.drop_column('variants', 'annotation_status')
    op.drop_column('variants', 'gnomad_an')
    op.drop_column('variants', 'gnomad_ac')
    op.drop_column('variants', 'gnomad_af')
    op.drop_column('variants', 'clinvar_condition')
    op.drop_column('variants', 'clinvar_review_status')
    op.drop_column('variants', 'clinvar_significance')
    op.drop_column('variants', 'protein_change')
    op.drop_column('variants', 'consequence')
    op.drop_column('variants', 'transcript_id')
    op.drop_column('variants', 'gene_symbol')
    # ### end Alembic commands ###
